// flow-typed signature: 7fde575518e88f0be562ef0b99d59185
// flow-typed version: <<STUB>>/gitbook-plugin-github_v^3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gitbook-plugin-github'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gitbook-plugin-github' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gitbook-plugin-github/_assets/plugin' {
  declare module.exports: any;
}

declare module 'gitbook-plugin-github/src/GitHubButtons' {
  declare module.exports: any;
}

declare module 'gitbook-plugin-github/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gitbook-plugin-github/_assets/plugin.js' {
  declare module.exports: $Exports<'gitbook-plugin-github/_assets/plugin'>;
}
declare module 'gitbook-plugin-github/index' {
  declare module.exports: $Exports<'gitbook-plugin-github'>;
}
declare module 'gitbook-plugin-github/index.js' {
  declare module.exports: $Exports<'gitbook-plugin-github'>;
}
declare module 'gitbook-plugin-github/src/GitHubButtons.js' {
  declare module.exports: $Exports<'gitbook-plugin-github/src/GitHubButtons'>;
}
declare module 'gitbook-plugin-github/src/index.js' {
  declare module.exports: $Exports<'gitbook-plugin-github/src/index'>;
}
