// flow-typed signature: 9c8bd7aaa5e72c757c7b0fe3a4f2b31e
// flow-typed version: <<STUB>>/gitbook-plugin-edit-link_v^2.0.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gitbook-plugin-edit-link'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gitbook-plugin-edit-link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gitbook-plugin-edit-link/book/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gitbook-plugin-edit-link/book/plugin.js' {
  declare module.exports: $Exports<'gitbook-plugin-edit-link/book/plugin'>;
}
declare module 'gitbook-plugin-edit-link/index' {
  declare module.exports: $Exports<'gitbook-plugin-edit-link'>;
}
declare module 'gitbook-plugin-edit-link/index.js' {
  declare module.exports: $Exports<'gitbook-plugin-edit-link'>;
}
