// flow-typed signature: c3d3f7609734d69639413bba5d1614b6
// flow-typed version: <<STUB>>/gitbook-plugin-anker-enable_v^0.0.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gitbook-plugin-anker-enable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gitbook-plugin-anker-enable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gitbook-plugin-anker-enable/book/anker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gitbook-plugin-anker-enable/book/anker.js' {
  declare module.exports: $Exports<'gitbook-plugin-anker-enable/book/anker'>;
}
declare module 'gitbook-plugin-anker-enable/index' {
  declare module.exports: $Exports<'gitbook-plugin-anker-enable'>;
}
declare module 'gitbook-plugin-anker-enable/index.js' {
  declare module.exports: $Exports<'gitbook-plugin-anker-enable'>;
}
