// flow-typed signature: bd7949155e1c7f4a5624253a3560528f
// flow-typed version: <<STUB>>/gitbook-plugin-advanced-emoji_v^0.2.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gitbook-plugin-advanced-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gitbook-plugin-advanced-emoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gitbook-plugin-advanced-emoji/pre-publish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gitbook-plugin-advanced-emoji/index' {
  declare module.exports: $Exports<'gitbook-plugin-advanced-emoji'>;
}
declare module 'gitbook-plugin-advanced-emoji/index.js' {
  declare module.exports: $Exports<'gitbook-plugin-advanced-emoji'>;
}
declare module 'gitbook-plugin-advanced-emoji/pre-publish.js' {
  declare module.exports: $Exports<'gitbook-plugin-advanced-emoji/pre-publish'>;
}
