// flow-typed signature: dc5bf6256471f96d2d7394cddec6d30f
// flow-typed version: <<STUB>>/gitbook-plugin-prism_v^2.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gitbook-plugin-prism'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gitbook-plugin-prism' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gitbook-plugin-prism/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gitbook-plugin-prism/index' {
  declare module.exports: $Exports<'gitbook-plugin-prism'>;
}
declare module 'gitbook-plugin-prism/index.js' {
  declare module.exports: $Exports<'gitbook-plugin-prism'>;
}
declare module 'gitbook-plugin-prism/test.js' {
  declare module.exports: $Exports<'gitbook-plugin-prism/test'>;
}
